export { useGetProfile } from './model/api/profileApi'
export { getInitData } from './model/selectors/getInitData/getInitData'
export { getProfileData } from './model/selectors/getProfileData/getProfileData'
export { profileActions, profileReducer } from './model/slice/profileSlice'
export type { Profile, ProfileSchema } from './model/types/Profile'
